require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/BlockForwarding:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*.rb'

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Style/ArgumentsForwarding:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/HashSyntax:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
